version: "3.8"

services:
  coder:
    image: ghcr.io/coder/coder:latest
    container_name: coder
    ports:
      - "7080:7080"
    environment:
      - CODER_ACCESS_URL=http://localhost:7080
      - CODER_HTTP_ADDRESS=0.0.0.0:7080
      - CODER_WILDCARD_ACCESS_URL=*.localhost:7080
      - CODER_PG_CONNECTION_URL=postgresql://coder:password@postgres:5432/coder?sslmode=disable
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./data:/home/coder/.config/coderv2
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped

  postgres:
    image: postgres:15
    container_name: coder-postgres
    environment:
      - POSTGRES_USER=coder
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=coder
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U coder -d coder"]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: unless-stopped

volumes:
  postgres_data: