version: "3.8"

services:
  coder:
    image: ghcr.io/coder/coder:latest
    container_name: coder
    ports:
      - "${CODER_PORT:-7080}:7080"
    env_file:
      - .env
    environment:
      - CODER_ACCESS_URL=${CODER_ACCESS_URL:-http://localhost:7080}
      - CODER_HTTP_ADDRESS=${CODER_HTTP_ADDRESS:-0.0.0.0:7080}
      - CODER_WILDCARD_ACCESS_URL=${CODER_WILDCARD_ACCESS_URL:-*.localhost:7080}
      - CODER_PG_CONNECTION_URL=postgresql://${POSTGRES_USER:-coder}:${POSTGRES_PASSWORD:-coder}@postgres:5432/${POSTGRES_DB:-coder}?sslmode=disable
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./data:/home/coder/.config/coderv2
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped

  postgres:
    image: postgres:15
    container_name: coder-postgres
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${POSTGRES_USER:-coder}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-coder}
      - POSTGRES_DB=${POSTGRES_DB:-coder}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U coder -d coder"]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: unless-stopped

volumes:
  postgres_data: